### ISSUE TITLE
Docs about using in dev mode

### ISSUE THREAD

**Issue by vrslev** [JohnPremKumar/vite-plugin-favicons-inject#3]
Plugin works only in prod mode, when running `vite build && vite preview`. When running in dev mode — `vite` — assets don't get built, only HTML is being injected. It happens because, I quote [Vite docs](https://vitejs.dev/guide/api-plugin.html#universal-hooks):
> [Output Generation Hooks](https://rollupjs.org/guide/en/#output-generation-hooks) (except closeBundle) are not called during dev. You can think of Vite's dev server as only calling rollup.rollup() without calling bundle.generate().

**Comment by JohnPremKumar** [comment]
This was a expected behaviour. Running favicon plugin image generation process in dev mode in can considerably slowdown HMR reloads. If don't want the favicons markup to be injected in dev mode. You can consider enabling it optionally in production mode alone. 

May it will be better if this behaviour is documented.

**Comment by vrslev** [comment]
Agreed: running `favicons` can't be considered "lightweight" 😅
I disabled the plugin roughly like this:

```ts
{
	plugins: [
		process.env.NODE_ENV == "production" ? vitePluginFaviconsInject() : null,
	],
},
```

> May it will be better if this behaviour is documented.

Absolutely!

**Comment by JohnPremKumar** [comment]
Docs Updated as suggested!

https://github.com/JohnPremKumar/vite-plugin-favicons-inject/tree/v2.2.0#development-mode
